'use client';
import { useRouter } from "next/navigation";
const FONT = "'Inter', system-ui, sans-serif";

const Section = ({ title, children }) => (
  <div style={{ marginBottom: 36 }}>
    <h2 style={{ fontSize: 16, fontWeight: 700, color: "#f1f5f9", marginBottom: 12 }}>{title}</h2>
    <div style={{ fontSize: 14, color: "#64748b", lineHeight: 1.9 }}>{children}</div>
  </div>
);

export default function Terms() {
  const router = useRouter();
  return (
    <div style={{ minHeight: "100vh", background: "#050810", fontFamily: FONT, color: "#f1f5f9" }}>

      <div style={{ position: "sticky", top: 0, zIndex: 10, background: "rgba(5,8,16,0.9)", backdropFilter: "blur(20px)", borderBottom: "1px solid rgba(255,255,255,0.06)", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 24px", height: 60 }}>
        <button onClick={() => router.back()} style={{ background: "none", border: "none", color: "#64748b", fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: FONT }}>← Back</button>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 26, height: 26, background: "linear-gradient(135deg, #10b981, #059669)", borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14 }}>🛡️</div>
          <span style={{ fontSize: 15, fontWeight: 800, color: "#f1f5f9" }}>BillVeil</span>
        </div>
        <div style={{ width: 60 }} />
      </div>

      <div style={{ maxWidth: 680, margin: "0 auto", padding: "56px 24px 80px" }}>
        <div style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: "#10b981", letterSpacing: "0.14em", marginBottom: 14 }}>LEGAL</div>
          <h1 style={{ fontSize: "clamp(28px, 5vw, 40px)", fontWeight: 900, letterSpacing: "-0.03em", color: "#f1f5f9", marginBottom: 12 }}>Terms of Service</h1>
          <p style={{ fontSize: 13, color: "#475569" }}>Last updated: January 2025</p>
        </div>

        <div style={{ background: "rgba(245,158,11,0.06)", border: "1px solid rgba(245,158,11,0.2)", borderRadius: 14, padding: "20px 22px", marginBottom: 40 }}>
          <div style={{ fontSize: 15, fontWeight: 700, color: "#fbbf24", marginBottom: 8 }}>⚠️ Important notice</div>
          <div style={{ fontSize: 14, color: "#64748b", lineHeight: 1.75 }}>
            BillVeil provides AI-generated information for educational purposes only. Nothing on this site constitutes medical, legal, or financial advice. Always consult a qualified professional before making decisions about your healthcare or finances.
          </div>
        </div>

        <Section title="1. Acceptance of terms">
          <p>By accessing or using BillVeil ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
        </Section>

        <Section title="2. Description of service">
          <p style={{ marginBottom: 10 }}>BillVeil provides AI-powered tools to help users understand medical bills, generate dispute letters, compare drug prices, and navigate insurance denials. The Service is provided free of charge.</p>
          <p>BillVeil is an informational tool only. We are not a law firm, medical practice, or financial advisory firm. Our AI-generated content does not constitute professional advice of any kind.</p>
        </Section>

        <Section title="3. Not medical, legal, or financial advice">
          <p style={{ marginBottom: 10 }}>All content generated by BillVeil is for informational and educational purposes only. It should not be relied upon as a substitute for professional medical, legal, billing, or financial advice.</p>
          <p>Always consult a qualified healthcare provider, attorney, or financial advisor for advice specific to your situation. BillVeil does not guarantee any specific outcome from using our tools, including bill reductions, claim approvals, or savings.</p>
        </Section>

        <Section title="4. Accuracy of information">
          <p style={{ marginBottom: 10 }}>BillVeil uses AI models trained on publicly available data about medical billing rates and insurance practices. While we strive for accuracy, we do not guarantee that our AI's analysis reflects current pricing, regulations, or your specific plan's terms.</p>
          <p>Fair market rate estimates are approximations based on Medicare data and market research. Actual costs vary significantly by location, provider, and insurance plan.</p>
        </Section>

        <Section title="5. User responsibilities">
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li>You are responsible for verifying all information before taking action based on BillVeil's output</li>
            <li>You agree not to use BillVeil for any unlawful purpose</li>
            <li>You agree not to submit false or fraudulent information</li>
            <li>You agree not to attempt to reverse-engineer, scrape, or abuse the Service</li>
            <li>You are solely responsible for the accuracy of the bill information you submit</li>
          </ul>
        </Section>

        <Section title="6. Intellectual property">
          <p>BillVeil and its content, features, and functionality are owned by BillVeil and are protected by copyright and other intellectual property laws. The AI-generated analysis provided to you is for your personal, non-commercial use only.</p>
        </Section>

        <Section title="7. Limitation of liability">
          <p>BillVeil is provided "as is" without warranties of any kind. To the maximum extent permitted by law, BillVeil and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service — including any outcome (positive or negative) resulting from acting on BillVeil's analysis.</p>
        </Section>

        <Section title="8. Indemnification">
          <p>You agree to indemnify and hold harmless BillVeil and its creators from any claims, damages, or expenses arising from your use of the Service or your violation of these Terms.</p>
        </Section>

        <Section title="9. Changes to terms">
          <p>We reserve the right to modify these Terms at any time. We will update the date at the top of this page. Continued use of BillVeil after changes constitutes acceptance of the updated Terms.</p>
        </Section>

        <Section title="10. Governing law">
          <p>These Terms are governed by the laws of the State of California, without regard to conflict of law principles.</p>
        </Section>

        <Section title="11. Contact">
          <p>Questions about these Terms? Contact us at <a href="mailto:hello@billveil.com" style={{ color: "#10b981" }}>hello@billveil.com</a></p>
        </Section>
      </div>
    </div>
  );
}
